language: node_js
node_js:
  - '4.4.7'
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
sudo: required
before_script: npm i
script:
  - npm run test
